### ISSUE TITLE
Store#toModel strips 'type' attributes

### ISSUE THREAD

**Issue by ryyppy** [confetti/yayson#23]
So, this is a very specific use-case, which we currently need in our application, so I might be biased in my question here :-)

Currently we have a data-model for our json-api, for which the attribute 'type' is very important for rendering specific components (in react).

I.e. you have tweets and a tweet may contain a sub-entity, which may be a link or another tweet (I call this json-api relationship 'sub_entity').

Now I queried all my tweets with included `sub_entity`, but those `sub_entity` lost it's type, since the yayson `Store` does not add this attribute to the model. So I don't know if I should use my 'Link-Component' or 'Sub-Tweet-Component'.

**What I got from Store#sync:**

```
{
   id: 'tweet1',
   sub_entity: {
      'id': 'se1'
   }
}
```

**What I actually want from Store#sync:**

```
{
  id: 'tweet1',
  type: 'tweet',
  sub_entity: {
      'id': 'se1',
      'type': 'link'
  }
}
```

This design may be questionable, but our system is built kinda like that.

**Second problem:**

Yayson currently wraps specific attributes in a get-function (i.e to wrap the links attribute).
This results of model objects being polluted with functions, although in my opinion, returned data should only consist of clean plain objects.

**So, my temporary solution right now is:**
- In the `Store#toModel` method, I add the type to the soon-to-return model
  - https://github.com/runtastic/yayson/blob/temp-release/src/yayson/store.coffee#L20
- Also, I added a constructor option for disabling the creation of  `get`-wrappers
  - https://github.com/runtastic/yayson/blob/temp-release/src/yayson/store.coffee#L10
  - Here the logic creating the `get`-fn: https://github.com/runtastic/yayson/blob/temp-release/src/yayson/store.coffee#L47-L49
  - This is designed as opt-out, that means it doesn't break currently existing code

Now, with my current implementation, I can use the store like in this green test-case:
https://github.com/runtastic/yayson/blob/temp-release/test/yayson/store.coffee#L112-L139

**My concrete questions to you are:**
- Is there any specific reason for the type not to be included in the returned denormalized model?
- Is there a specific use-case why we need the `get`-function? (although I made this optional, it is not too important)

I hope you understand my problem and maybe you find this code changes helpful, if so I will be happy to create a PR :-)

**Comment by afazio** [comment]
+1 on both of these issues.  Thanks @magicpat!

**Comment by abrykajlo** [comment]
+1 for id and type stripping

**Comment by abrykajlo** [comment]
@magicpat @afazio the temporary fix that I am using is commenting out [this and the following line](https://github.com/confetti/yayson/blob/0748aa5230fb992189f5e3b25a177627b6046e54/src/yayson/presenter.coffee#L28) which translates to removing [these](https://github.com/confetti/yayson/blob/26ca0784201f775a567c4a5ae7bd5dd7b2624c2e/dist/yayson.js#L5154) in the distribution.

**Comment by afazio** [comment]
@abrykajlo Thanks Adam!

**Comment by ryyppy** [comment]
@abrykajlo I actually never used the Presenter, but the problem looks similar to mine :+1:

**Comment by ryyppy** [comment]
@jede What do you think? I already got another sync feature which would be interesting for a PR, targeting meta-attributes ;-)

**Comment by jede** [comment]
Hi! Sorry for my slowness :grimacing: I think this sounds really promising! To answer your questions, the type should be included in my opinion. It looks like we should remove the get-method. It was added in your earlier pull request: https://github.com/confetti/yayson/pull/19 . But by the looks of it it doesn't do much, right?

**Comment by ryyppy** [comment]
Hey! Sadly I forgot that I mentioned the (now deleted) "temp-release" branch in our forked repository, so my references are broken.

Unfortunately since I opened this thread we made a fork which adapts more to our use-cases for the response-denormalization process. It still sticks to the JSONAPI-standard, but we enhanced Store parametrization and stuff.

Maybe you like some ideas, here are the changes:
- Include type attribute
- Gather meta / links attributes in the entity top level (each can be enabled via flags)
- (The meta nesting has some downsides, but only in certain response conditions)
- Store#syncWithMeta() -> Obviously adds meta attribute to resolved entities
- Full motivation + input / output example: https://github.com/runtastic/yayson/tree/v3

Although the "get-approach" was a cool idea, we could not use it since we require pure JS objects... I wanted to access relationship links / meta directly, so here we go :-)

So I consider this thread kinda closed, unless you want me to make an official PR for an one-liner ;-)

Have a nice evening!

**Comment by ryyppy** [comment]
Ah and something else: 
In my experience, this LIB's got the cleanest approach of resolving the entities from a JSONAPI response... all the other libs are super annoying to handle / include, so we have been considering to port it to actual ES6!

**Comment by jede** [comment]
Thanks! Great feedback, I'll make sure to add the type!

**Comment by jede** [comment]
In version 2.0.1 type is added in the store and the get method is removed!
