### ISSUE TITLE
Presenters Question

### ISSUE THREAD

**Issue by leviwilson** [confetti/yayson#25]
This is less of an issue and more of a question for me; apologies if I'm slow, but I was having trouble figuring out what the presenters were doing for me?

When I get a JSON API response back, I do a `store.sync request.data` and get a flattened object, which is great! However, what I'd _hoped_ to leverage the `Presenter` for was to add "helper methods" to my models and have `yayson` know about them. That _appeared_ to be what it was, but that doesn't seem to work?

I thought I could do something like this:

``` coffeescript
class PersonPresenter extends Presenter
  type: 'person'
  getFullName: -> "#{@data.attributes.first_name} #{@data.attributs.last_name}"
```

and I would get an object just like the `Store` gives you, but enhanced with my helper method:

``` javascript
{
  first_name: 'Levi',
  last_name: 'Wilson',
  getFullName: function() {
    return this.first_name + ' ' + this.last_name;
  }
}
```

The only way I get this is if I add it underneath `attributes` like so:

``` coffeescript
class PersonPresenter extends Presenter
  type: 'person'
  attributes: ->
    attrs = super
    attrs.getFullName = -> "#{@data.attributes.first_name} #{@data.attributs.last_name}"
```

What am I missing here? Or am I completely missing the intention of the `Presenter` and what it is used for?

**Comment by jede** [comment]
Hi!

The presenters are used for generating JSON API valid JSON, so the store doesn't use the presenters. 

I guess you could create a custom store and extend the `toModel` method and add you're own helpers there?

**Comment by leviwilson** [comment]
Ahh, that was my misunderstanding. It's going the other direction _completely_. I understand, now. My first client-side library I used was `angular-jsonapi`, so I was trying to find equivalent functionality that it provided with how it defined resources.

Thanks for the info!
