### ISSUE TITLE
Add Yayson to Bower

### ISSUE THREAD

**Issue by walterg2** [confetti/yayson#26]
It would be nice to have Yayson able to be loaded via Bower. 

If you're looking/would want to do this, I would be happy to submit a PR regarding it.

**Comment by jede** [comment]
Hi there!

Now its registered! Just run `bower install yayson` and all your dreams will come true ;)

**Comment by cheerfulstoic** [comment]
This is great, thanks!

As I understand it, all we should need is the `dist/yayson.js` file, right?  Does it make sense to add `src` to the `ignore` array?

**Comment by jede** [comment]
Yes! Thats the point! Hm, maybe... I was thinking that people using coffescript and webpack for instance wanted to use the original files.

**Comment by cheerfulstoic** [comment]
Ah, maybe ;)  I'm down with that.  We actually use coffeescript, though I'm not very familiar with webpack.  We're using Rails currently and it's nice just to be able to specify the one file to bring in yayson as a dependency.  But perhaps we can do that with the coffee files and I just don't know how
