### ISSUE TITLE
Warning when requiring lodash.underscore in webpack

### ISSUE THREAD

**Issue by robwagner33** [confetti/yayson#32]
**Issue:**

In lib/yayson.js:

`require('lodash/dist/lodash.underscore')`

If using a newer version of lodash in your project, webpack will warn that it cannot resolve this module. Importing yayson will give a warning since it won't be able to find that module in the default 'node_modules' directory.

**Warning:**

`Module not found: Error: Can't resolve 'lodash/dist/lodash.underscore' in <workspace>/node_modules/yayson/lib`

**Replicating:**

Create a new project that requires a newer version of lodash than yayson uses.  The require will give a warning, as it will not be able to find lodash/dist/lodash.underscore under the the project-level 'node_modules' or relative the the yasyon.js in 'lib'

```
  ...
  "dependencies": {
    "lodash": "^4",
    "yayson": "2.0.5"
  }
```

**Workaround:**

You can workaround this warning by telling webpack to explicitly look within yayson to resolve the module as well, but this is not ideal. I know that other packages must deal with dependency requires in some other way, so I suspect something may be atypical here.

**Comment by jede** [comment]
I've updated lodash to the latest version and changed how its required (i guess the old underscore compatibility was the problem). Please let me know if the problem persists!

**Comment by robwagner33** [comment]
Hey @jede , thanks for taking a look at this! This is a pretty low-priority for me, but is just a minor annoyance to see in the build. I've put up a PR for another require that needs updated.
