### ISSUE TITLE
Wrong path for main in package.json

### ISSUE THREAD

**Issue by PhilippMi** [confetti/yayson#6]
`"main": "lib/yayson.js"` should be `"main": "dist/yayson.js"`

**Comment by jede** [comment]
Hm, well yes and no. The dist file is aimed at browser use. When used in a node env its better to include the file from lib so we use nodes require functionallity and don't add the webpack overhead. It also makes debugging easier and stack traces nicer.

**Comment by jede** [comment]
Oh, but the lib has went missing. Strange. I'll look into it!

**Comment by jede** [comment]
Ok, so the published npm package contains the lib directory, but since its compiled we didn't want to put it on github so someone doesn't make a pull request with changes to it. The dist file is just here to make it easier to use without installing everything. Sorry for the confusion :)
