### ISSUE TITLE
TypeError: Class constructor Presenter cannot be invoked without 'new'

### ISSUE THREAD

**Issue by hult** [confetti/yayson#75]
Hi @javve @jede et. al.!

We've been using yayson in ES6 like this

```javascript
import yayson from 'yayson'
const y = yayson({adapter: 'default'})
const Presenter = y.Presenter

class MyPresenter extends Presenter {
  // ...
}

class AnotherPresenter extends MyPresenter {
  attributes(instance) {
    // We don't want to send the image to the server
    var attrs = super.attributes(instance)
    delete attrs['image']
    return attrs
  }
}
AnotherPresenter.prototype.type = 'another_type'
```

And it has worked well up until version 2.0.8. Starting in yayson 2.0.9, we get the error

```
TypeError: Class constructor Presenter cannot be invoked without 'new'

      59 |     delete attrs['image']
      60 |     return attrs
    > 61 |   }
         |    ^
      62 | }
```

Something has changed. Any ideas?

**Comment by jede** [comment]
Hm, interesting. 2.0.9 was a veryminor change, there is however an effort to remove CoffeeScript. Maybe try out that branch? https://github.com/confetti/yayson/pull/69

**Comment by hult** [comment]
> 2.0.9 was a very minor change

Yeah I saw, but 2.0.8 was a while ago, and quite a few dependencies were updated since.

> Maybe try out that branch?

Will do!

> #69

Nice.

**Comment by hult** [comment]
(Sorry for not understanding how coffeescript modules work at all. :( )

If I `yarn add https://github.com/confetti/yayson.git#decaffeinate`, I get the exact same error as above.

If I try to install any commit between 2.0.8 and 2.0.9 (to pinpoint when the error appeared), I instead get the error `Cannot find module 'yayson'` (I guess it isn't automatically transpiled?)

**Comment by jede** [comment]
I think there is a release issue that @javve tried to fix with v2.0.10-quickfix, but I'm not sure it worked. Are you running your example in the browser (and in that case are you using webpack or something else?) or in node?

**Comment by hult** [comment]
This is for the browser, with webpack (4.41.5). 2.0.10-quickfix didn't fix my problem unfortunately.

**Comment by hult** [comment]
(Also, I'm perfectly happy with 2.0.8, don't work too hard on this. :))

**Comment by jede** [comment]
This probably has to do with extending non native ES6 classes. Its wierd that it worked pre 2.0.9 though. I think this will be solved in 3.0 when everything will be native classes :) And I really havn't been working hard on this! 😂

**Comment by hult** [comment]
🥰😍😘❤️ (In my head, you both worked full-time on this since February last
year, no matter what you say.)

**Comment by jede** [comment]
A brand new 3.0 version is finally out 😅
