### ISSUE TITLE
Install latest version

### ISSUE THREAD

**Issue by andresberrios** [confetti/yayson#9]
Hi! I can't seem to be able to install through npm the latest version (with the last couple of pull requests merged in).
I tried pointing in package.json to `"https://github.com/confetti/yayson/archive/master.zip"` and it crashes on install.
I also tried `"confetti/yayson"`, `"confetti/yayson#50985ab7bf8b91eab7a3e261991959b949a4ccac"`, `"git+https://github.com/confetti/yayson.git#50985ab7bf8b91eab7a3e261991959b949a4ccac"` and they all install without errors but the actual code is not among the installed files...
Also tried installing from my fork, with the same results.
Please help!

**Comment by jede** [comment]
Hm, thats wierd. Anyway I've released the yayson@2.0.0-beta.5 with the fixes included now!

**Comment by andresberrios** [comment]
Ah great! Tack!
